language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  global:
    - DJANGO_SETTINGS_MODULE=staticinline.tests.testapp.settings
  matrix:
    - DJANGO=1.8.*
    - DJANGO=1.9.*
    - DJANGO=1.10.*
    - DJANGO=1.11.*
    - DJANGO=2.0.*

matrix:
  exclude:
    - python: 2.7
      env: DJANGO=2.0.*

before_install:
  - pip install coverage codacy-coverage
  - coverage erase

install:
  - pip install django==$DJANGO
  - pip install -e .[tests]

script:
  - coverage run --append ./runtests.py

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
